# Generated by Django 4.0.2 on 2023-01-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_order_tag_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('starters', 'Starters'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('burgers', 'Burgers'), ('fries', 'Fries')], max_length=200, null=True),
        ),
    ]
